apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-initializer
data:
  config: |
      - name: secure
        label: database
        attributes: '{"dmcrypt": "enabled", "dmcrypt-key": "some-key" }'
      - name: normal
        label: web
        attributes: '{ "dmcrypt": "disabled"}'

