apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    role: web-frontend
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
          - name: my-disk
            mountPath: "/usr/share/nginx/html"
      volumes:
        - name: my-disk
          persistentVolumeClaim:
            claimName: my-pvc
